# Gradle Settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Mod Properties
mod_version=1.0.0
maven_group=com.lowres.performance
archives_base_name=sodium-compat-layer

# Fabric Properties (Versões TRAVADAS para funcionar)
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.3
loader_version=0.17.0

# Loom e API (Versões estáveis)
loom_version=1.14-SNAPSHOT
fabric_version=0.138.4+1.21.10